[2022-11-07T23:14:00.680+0000] {processor.py:154} INFO - Started process (PID=1857) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:00.682+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:14:00.685+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:14:00.684+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:00.677+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:14:00.694+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:14:00.680+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:00.724+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.084 seconds
[2022-11-07T23:14:31.177+0000] {processor.py:154} INFO - Started process (PID=1924) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:31.179+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:14:31.181+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:14:31.181+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:31.190+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:14:31.189+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:14:31.192+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:14:31.230+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.058 seconds
[2022-11-07T23:15:01.593+0000] {processor.py:154} INFO - Started process (PID=1980) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:01.597+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:15:01.599+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:15:01.599+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:01.619+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:15:01.616+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:15:01.625+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:01.673+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.086 seconds
[2022-11-07T23:15:31.911+0000] {processor.py:154} INFO - Started process (PID=2048) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:31.915+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:15:31.916+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:15:31.916+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:31.924+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:15:31.923+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:15:31.925+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:15:31.956+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.051 seconds
[2022-11-07T23:16:02.742+0000] {processor.py:154} INFO - Started process (PID=2114) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:02.746+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:16:02.754+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:16:02.752+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:02.772+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:16:02.768+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:16:02.777+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:02.824+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.087 seconds
[2022-11-07T23:16:33.473+0000] {processor.py:154} INFO - Started process (PID=2171) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:33.476+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:16:33.479+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:16:33.479+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:33.505+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:16:33.493+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:16:33.511+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:16:33.562+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.095 seconds
[2022-11-07T23:17:04.271+0000] {processor.py:154} INFO - Started process (PID=2238) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:04.273+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:17:04.276+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:17:04.276+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:04.286+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:17:04.284+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:17:04.288+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:04.325+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.059 seconds
[2022-11-07T23:17:34.452+0000] {processor.py:154} INFO - Started process (PID=2296) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:34.454+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:17:34.456+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:17:34.456+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:34.464+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:17:34.463+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:17:34.465+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:17:34.493+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.045 seconds
[2022-11-07T23:18:05.483+0000] {processor.py:154} INFO - Started process (PID=2362) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:05.485+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:18:05.487+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:18:05.486+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:05.495+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:18:05.493+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:18:05.496+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:05.532+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.053 seconds
[2022-11-07T23:18:36.015+0000] {processor.py:154} INFO - Started process (PID=2431) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:36.019+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:18:36.025+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:18:36.024+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:36.057+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:18:36.054+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:18:36.060+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:18:36.113+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.106 seconds
[2022-11-07T23:19:07.025+0000] {processor.py:154} INFO - Started process (PID=2488) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:07.029+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:19:07.033+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:19:07.032+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:07.045+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:19:07.044+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:19:07.047+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:07.096+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.082 seconds
[2022-11-07T23:19:37.893+0000] {processor.py:154} INFO - Started process (PID=2558) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:37.896+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:19:37.899+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:19:37.899+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:37.917+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:19:37.914+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:19:37.919+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:19:37.962+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2022-11-07T23:20:08.876+0000] {processor.py:154} INFO - Started process (PID=2615) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:08.988+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:20:09.010+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:20:09.010+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:09.073+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:20:09.062+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:20:09.084+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:09.272+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.422 seconds
[2022-11-07T23:20:39.556+0000] {processor.py:154} INFO - Started process (PID=2674) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:39.559+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:20:39.563+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:20:39.562+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:39.580+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:20:39.577+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:20:39.581+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:20:39.619+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.071 seconds
[2022-11-07T23:21:10.033+0000] {processor.py:154} INFO - Started process (PID=2741) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:10.036+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:21:10.038+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:21:10.037+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:10.045+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:21:10.044+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:21:10.046+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:10.078+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.049 seconds
[2022-11-07T23:21:40.644+0000] {processor.py:154} INFO - Started process (PID=2798) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:40.648+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:21:40.651+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:21:40.651+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:40.664+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:21:40.662+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:21:40.667+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:21:40.718+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.082 seconds
[2022-11-07T23:22:11.115+0000] {processor.py:154} INFO - Started process (PID=2865) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:11.117+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:22:11.119+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:22:11.119+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:11.126+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:22:11.125+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:22:11.128+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:11.159+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.049 seconds
[2022-11-07T23:22:41.332+0000] {processor.py:154} INFO - Started process (PID=2921) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:41.334+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:22:41.336+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:22:41.336+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:41.346+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:22:41.344+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:22:41.349+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:22:41.390+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.062 seconds
[2022-11-07T23:23:11.584+0000] {processor.py:154} INFO - Started process (PID=2991) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:11.586+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:23:11.588+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:23:11.588+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:11.596+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:23:11.595+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:23:11.598+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:11.630+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.051 seconds
[2022-11-07T23:23:41.944+0000] {processor.py:154} INFO - Started process (PID=3048) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:41.947+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:23:41.948+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:23:41.948+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:41.958+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:23:41.956+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:23:41.960+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:23:42.011+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.072 seconds
[2022-11-07T23:24:12.321+0000] {processor.py:154} INFO - Started process (PID=3116) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:12.323+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:24:12.325+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:24:12.325+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:12.334+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:24:12.333+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:24:12.336+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:12.375+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.058 seconds
[2022-11-07T23:24:42.920+0000] {processor.py:154} INFO - Started process (PID=3171) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:42.922+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:24:42.925+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:24:42.924+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:42.938+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:24:42.936+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:24:42.940+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:24:42.979+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.063 seconds
[2022-11-07T23:25:13.479+0000] {processor.py:154} INFO - Started process (PID=3237) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:13.481+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:25:13.484+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:25:13.483+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:13.496+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:25:13.494+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:25:13.498+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:13.540+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.076 seconds
[2022-11-07T23:25:44.170+0000] {processor.py:154} INFO - Started process (PID=3303) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:44.174+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:25:44.176+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:25:44.175+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:44.186+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:25:44.184+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:25:44.188+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:25:44.231+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.068 seconds
[2022-11-07T23:26:14.977+0000] {processor.py:154} INFO - Started process (PID=3359) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:14.979+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:26:14.981+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:26:14.980+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:14.992+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:26:14.990+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:26:14.993+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:15.034+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.063 seconds
[2022-11-07T23:26:45.643+0000] {processor.py:154} INFO - Started process (PID=3426) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:45.645+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:26:45.648+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:26:45.648+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:45.657+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:26:45.655+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:26:45.660+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:26:45.694+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.056 seconds
[2022-11-07T23:27:21.994+0000] {processor.py:154} INFO - Started process (PID=3491) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:27:22.009+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:27:22.021+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:27:22.017+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:27:22.057+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:27:22.053+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:27:22.076+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:27:22.200+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.232 seconds
[2022-11-07T23:28:28.678+0000] {processor.py:154} INFO - Started process (PID=3501) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:28:28.684+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:28:28.688+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:28:28.688+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:28:28.707+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:28:28.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:28:28.710+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:28:28.763+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.093 seconds
[2022-11-07T23:28:59.903+0000] {processor.py:154} INFO - Started process (PID=3557) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:28:59.911+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:28:59.919+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:28:59.918+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:28:59.989+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:28:59.937+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:28:59.994+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:29:00.127+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.240 seconds
[2022-11-07T23:29:30.815+0000] {processor.py:154} INFO - Started process (PID=3624) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:29:30.817+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:29:30.819+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:29:30.819+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:29:30.829+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:29:30.827+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:29:30.831+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:29:30.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.057 seconds
[2022-11-07T23:30:00.965+0000] {processor.py:154} INFO - Started process (PID=3682) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:00.967+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:30:00.969+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:30:00.969+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:00.981+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:30:00.979+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:30:00.984+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:01.022+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.062 seconds
[2022-11-07T23:30:31.363+0000] {processor.py:154} INFO - Started process (PID=3750) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:31.365+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:30:31.367+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:30:31.367+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:31.375+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:30:31.373+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:30:31.376+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:30:31.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.064 seconds
[2022-11-07T23:31:01.560+0000] {processor.py:154} INFO - Started process (PID=3807) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:01.564+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:31:01.567+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:31:01.567+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:01.594+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:31:01.582+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:31:01.600+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:01.658+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.106 seconds
[2022-11-07T23:31:32.211+0000] {processor.py:154} INFO - Started process (PID=3876) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:32.214+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:31:32.216+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:31:32.216+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:32.229+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:31:32.226+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:31:32.233+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:31:32.296+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.091 seconds
[2022-11-07T23:32:02.821+0000] {processor.py:154} INFO - Started process (PID=3932) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:02.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:32:02.835+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:32:02.834+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:02.857+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:32:02.855+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:32:02.859+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:02.896+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.081 seconds
[2022-11-07T23:32:33.412+0000] {processor.py:154} INFO - Started process (PID=3998) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:33.414+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:32:33.417+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:32:33.417+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:33.427+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:32:33.425+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:32:33.431+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:32:33.466+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.062 seconds
[2022-11-07T23:33:03.762+0000] {processor.py:154} INFO - Started process (PID=4055) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:03.765+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:33:03.768+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:33:03.768+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:03.778+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:33:03.777+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:33:03.780+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:03.816+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.064 seconds
[2022-11-07T23:33:33.882+0000] {processor.py:154} INFO - Started process (PID=4123) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:33.886+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:33:33.888+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:33:33.888+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:33.900+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:33:33.898+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:33:33.902+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:33:33.941+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.064 seconds
[2022-11-07T23:34:04.201+0000] {processor.py:154} INFO - Started process (PID=4180) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:04.204+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:34:04.206+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:34:04.206+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:04.217+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:34:04.215+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:34:04.220+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:04.266+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2022-11-07T23:34:34.641+0000] {processor.py:154} INFO - Started process (PID=4248) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:34.643+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:34:34.645+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:34:34.645+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:34.653+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:34:34.652+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:34:34.655+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:34:34.693+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.057 seconds
[2022-11-07T23:35:05.138+0000] {processor.py:154} INFO - Started process (PID=4303) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:05.142+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:35:05.145+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:35:05.145+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:05.161+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:35:05.158+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:35:05.163+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:05.212+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.079 seconds
[2022-11-07T23:35:36.134+0000] {processor.py:154} INFO - Started process (PID=4370) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:36.140+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:35:36.145+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:35:36.144+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:36.191+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:35:36.171+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:35:36.197+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:35:36.299+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.197 seconds
[2022-11-07T23:36:06.474+0000] {processor.py:154} INFO - Started process (PID=4426) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:06.477+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:36:06.479+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:36:06.479+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:06.492+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:36:06.489+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:36:06.494+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:06.537+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2022-11-07T23:36:36.701+0000] {processor.py:154} INFO - Started process (PID=4483) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:36.703+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:36:36.706+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:36:36.705+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:36.717+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:36:36.715+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:36:36.720+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:36:36.767+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.074 seconds
[2022-11-07T23:37:07.274+0000] {processor.py:154} INFO - Started process (PID=4551) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:07.277+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:37:07.280+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:37:07.279+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:07.294+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:37:07.292+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:37:07.297+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:07.337+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.069 seconds
[2022-11-07T23:37:37.839+0000] {processor.py:154} INFO - Started process (PID=4608) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:37.843+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:37:37.846+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:37:37.845+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:37.857+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:37:37.855+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:37:37.858+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:37:37.922+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.094 seconds
[2022-11-07T23:38:08.074+0000] {processor.py:154} INFO - Started process (PID=4673) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:08.077+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:38:08.079+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:38:08.079+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:08.088+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:38:08.087+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:38:08.090+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:08.120+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.051 seconds
[2022-11-07T23:38:38.335+0000] {processor.py:154} INFO - Started process (PID=4730) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:38.338+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:38:38.341+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:38:38.340+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:38.355+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:38:38.352+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:38:38.357+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:38:38.422+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.093 seconds
[2022-11-07T23:39:08.513+0000] {processor.py:154} INFO - Started process (PID=4787) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:08.515+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:39:08.517+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:39:08.516+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:08.525+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:39:08.523+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:39:08.527+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:08.556+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.050 seconds
[2022-11-07T23:39:38.996+0000] {processor.py:154} INFO - Started process (PID=4853) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:38.997+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:39:38.999+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:39:38.999+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:39.007+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:39:39.006+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:39:39.008+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:39:39.044+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.052 seconds
[2022-11-07T23:40:09.945+0000] {processor.py:154} INFO - Started process (PID=4918) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:09.948+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:40:09.950+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:40:09.949+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:09.959+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:40:09.958+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:40:09.962+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:09.999+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.058 seconds
[2022-11-07T23:40:40.823+0000] {processor.py:154} INFO - Started process (PID=4980) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:40.825+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:40:40.827+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:40:40.827+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:40.836+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:40:40.834+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:40:40.837+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:40:40.867+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.048 seconds
[2022-11-07T23:41:11.200+0000] {processor.py:154} INFO - Started process (PID=5047) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:11.203+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:41:11.205+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:41:11.205+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:11.214+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:41:11.213+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:41:11.216+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:11.253+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.059 seconds
[2022-11-07T23:41:41.619+0000] {processor.py:154} INFO - Started process (PID=5103) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:41.621+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:41:41.623+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:41:41.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:41.631+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:41:41.630+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:41:41.633+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:41:41.665+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.051 seconds
[2022-11-07T23:53:01.453+0000] {processor.py:154} INFO - Started process (PID=5138) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:01.460+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:53:01.463+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:53:01.463+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:01.488+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:53:01.483+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:53:01.494+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:01.603+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.156 seconds
[2022-11-07T23:53:32.284+0000] {processor.py:154} INFO - Started process (PID=5206) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:32.287+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:53:32.288+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:53:32.288+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:32.297+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:53:32.295+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:53:32.299+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:53:32.388+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.112 seconds
[2022-11-07T23:54:02.515+0000] {processor.py:154} INFO - Started process (PID=5262) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:02.517+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:54:02.519+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:54:02.518+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:02.530+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:54:02.528+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:54:02.532+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:02.575+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.071 seconds
[2022-11-07T23:54:32.687+0000] {processor.py:154} INFO - Started process (PID=5330) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:32.689+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:54:32.691+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:54:32.691+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:32.701+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:54:32.700+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:54:32.702+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:54:32.732+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.050 seconds
[2022-11-07T23:55:03.091+0000] {processor.py:154} INFO - Started process (PID=5385) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:03.094+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:55:03.097+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:55:03.096+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:03.106+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:55:03.103+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:55:03.108+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:03.140+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.053 seconds
[2022-11-07T23:55:33.351+0000] {processor.py:154} INFO - Started process (PID=5452) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:33.354+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:55:33.356+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:55:33.356+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:33.365+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:55:33.363+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:55:33.367+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:55:33.406+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.061 seconds
[2022-11-07T23:56:03.692+0000] {processor.py:154} INFO - Started process (PID=5509) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:03.696+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:56:03.697+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:56:03.697+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:03.706+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:56:03.704+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:56:03.707+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:03.743+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.054 seconds
[2022-11-07T23:56:33.817+0000] {processor.py:154} INFO - Started process (PID=5576) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:33.819+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:56:33.825+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:56:33.825+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:33.834+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:56:33.833+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:56:33.836+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:56:33.869+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.059 seconds
[2022-11-07T23:57:04.002+0000] {processor.py:154} INFO - Started process (PID=5635) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:04.004+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:57:04.006+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:57:04.006+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:04.017+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:57:04.015+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:57:04.019+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:04.064+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.070 seconds
[2022-11-07T23:57:34.234+0000] {processor.py:154} INFO - Started process (PID=5705) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:34.237+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:57:34.239+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:57:34.239+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:34.248+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:57:34.246+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:57:34.249+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:57:34.286+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.057 seconds
[2022-11-07T23:58:04.597+0000] {processor.py:154} INFO - Started process (PID=5762) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:04.600+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:58:04.602+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:58:04.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:04.610+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:58:04.608+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:58:04.611+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:04.643+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.050 seconds
[2022-11-07T23:58:35.055+0000] {processor.py:154} INFO - Started process (PID=5830) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:35.060+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:58:35.065+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:58:35.065+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:35.083+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:58:35.079+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:58:35.087+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:58:35.147+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.100 seconds
[2022-11-07T23:59:05.618+0000] {processor.py:154} INFO - Started process (PID=5896) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:05.621+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:59:05.623+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:05.623+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:05.634+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:05.633+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6
    
    ^
SyntaxError: unexpected EOF while parsing
[2022-11-07T23:59:05.636+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:05.680+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.068 seconds
[2022-11-07T23:59:16.455+0000] {processor.py:154} INFO - Started process (PID=5915) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:16.458+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:59:16.461+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:16.460+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:16.529+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:16.524+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6, in <module>
    train_mode_A = PythonOperator(
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2022-11-07T23:59:16.532+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:16.592+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.143 seconds
[2022-11-07T23:59:47.597+0000] {processor.py:154} INFO - Started process (PID=5972) to work on /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:47.599+0000] {processor.py:756} INFO - Processing file /opt/airflow/dags/my_dag.py for tasks to queue
[2022-11-07T23:59:47.601+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:47.601+0000] {dagbag.py:537} INFO - Filling up the DagBag from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:47.632+0000] {logging_mixin.py:120} INFO - [2022-11-07T23:59:47.627+0000] {dagbag.py:342} ERROR - Failed to import: /opt/airflow/dags/my_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 338, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/my_dag.py", line 6, in <module>
    train_mode_A = PythonOperator(
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 391, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'python_callable'
[2022-11-07T23:59:47.634+0000] {processor.py:768} WARNING - No viable dags retrieved from /opt/airflow/dags/my_dag.py
[2022-11-07T23:59:47.668+0000] {processor.py:176} INFO - Processing /opt/airflow/dags/my_dag.py took 0.075 seconds
